### ISSUE TITLE
Is there a way to uncenter the body？

### ISSUE THREAD

**Issue by zhangchi0104** [dbenitez-bcn/solid_bottom_sheet#23]
Hi, thanks for the widget.
I am wondering if there is any way to uncenter the body

**Comment by dbenitez-bcn** [comment]
What do you mean by uncenter?

**Comment by zhangchi0104** [comment]
I mean the body of the bottom sheet is always fixed(i.e. vertically centered).  It would be nice to have an option to set the alignment.

I have fixed the problem by wrapping the body with a `Container`  and set the `alignment` of the container to `Alignment.topCenter` so the content is always at the top of the body.

**Comment by dbenitez-bcn** [comment]
I would be nice, for sure. But I can't see the value of adding it because, as you said, it's easy to 'fix'. The think is that I don't believe that SolidBottomSheet should have the responsibility of positioning child widgets. Also, SolidBottomSheet doesn't know how large will be its child so would be a little confusing maybe aligning it... But I will keep in mind you suggestion and add it in the coming version maybe. 
Thanks for your support.
